### PR TITLE
Add `silent` configuration

### PR DESCRIPTION
**Pull request by brunops**
- `silent` default to `false`, so the module works as before
if nothing more is passed
- This feature prevents `beaver-logger` from logging on the window
when not wanted, this is good on production.
- Add `karma start` to `test` npm task

### CODE REVIEW

**Comment by brunops** [comment]
Let me know if you need me to bump the version and add the new bundle to `dist/` in this PR

**Comment by mstuart** [comment]
All good.  I'll bump and publish

**Comment by mstuart** [comment]
`+ beaver-logger@1.0.15`

**Comment by mstuart** [comment]
thx @brunops! 👍

**Pull request merged**
