### PR TITLE
feature/tracking_timestamp

### PR DESCRIPTION
**Pull request by mnicpt**
- Adds a client timestamp to FPTI logs

### CODE REVIEW

**Review by gregjopa — APPROVED** [review]
Looks good to me!

What is the difference between the `timestamp` and `t` keys w/ the tracking payload?

**Comment by mnicpt** [comment]
@gregjopa `timestamp` isn't indexed.  So I changed it to be `t`, which is.

**Comment by bluepnume** [comment]
Just thinking... since this is a generic library, and different backends will expect different keys, does it make more sense to just allow clients to use `addTrackingBuilder()` to add their own automatic timestamp key?

**Comment by mnicpt** [comment]
@bluepnume Yes.  Very good point!  I'll close this out and open one for SPB.

**Pull request closed without merging**
