### PR TITLE
Handle window.location undefined

### LINKED ISSUE #25: React Native - window.location.protocol undefined
When using this package in a React Native app there is an issue with window.location being undefined.  This causes an issue here:
https://github.com/krakenjs/beaver-logger/blob/master/src/logger.js#L105

### PR DESCRIPTION
**Pull request by daniel-shuy**
Fixes #25

`window.location` is `undefined` in React Native

### CODE REVIEW

**Comment by bluepnume** [comment]
Hi -- thanks for the fix, but isn't this already covered by `isBrowser()`?

**Comment by daniel-shuy** [comment]
No, [isBrowser()](https://github.com/krakenjs/belter/blob/v1.0.141/src/dom.js#L239-L241) only checks whether `window` is `undefined`, not `window.location`. React Native polyfills `window`, but not `window.location` (see https://github.com/facebook/react-native/blob/v0.63.3/Libraries/Core/setUpGlobals.js#L21-L23)

**Comment by daniel-shuy** [comment]
Or should I create a PR to update `isBrowser()` to check for `window.location` instead?

**Comment by bluepnume** [comment]
Gotcha. In that case would you mind making the fix in `isBrowser()` instead since the current implementation doesn't cover that react native case? Thanks!

**Comment by daniel-shuy** [comment]
Done (krakenjs/belter#11)

**Pull request closed without merging**
